// <auto-generated />
using Cool_Co_Fridge_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cool_Co_Fridge_Management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240808090425_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cool_Co_Fridge_Management.Models.Fridge_Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockID"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("FridgeTypeID")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockID");

                    b.HasIndex("FridgeTypeID");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("Cool_Co_Fridge_Management.Models.Fridge_Type", b =>
                {
                    b.Property<int>("FridgeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FridgeTypeID"));

                    b.Property<bool>("Availablity")
                        .HasColumnType("bit");

                    b.Property<string>("FridgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("FridgeTypeID");

                    b.HasIndex("SupplierID");

                    b.ToTable("fridge_type");

                    b.HasData(
                        new
                        {
                            FridgeTypeID = 1,
                            Availablity = true,
                            FridgeType = "Chest Freezer",
                            SupplierID = 789
                        },
                        new
                        {
                            FridgeTypeID = 2,
                            Availablity = true,
                            FridgeType = "Drawer Fridge",
                            SupplierID = 456
                        },
                        new
                        {
                            FridgeTypeID = 3,
                            Availablity = true,
                            FridgeType = "Commercial Fridge",
                            SupplierID = 123
                        },
                        new
                        {
                            FridgeTypeID = 4,
                            Availablity = true,
                            FridgeType = "Mini Fridge",
                            SupplierID = 101
                        },
                        new
                        {
                            FridgeTypeID = 5,
                            Availablity = true,
                            FridgeType = "French Door Fridge",
                            SupplierID = 112
                        });
                });

            modelBuilder.Entity("Cool_Co_Fridge_Management.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 789,
                            ContactNumber = "0860884402",
                            Email = "service@kic.co.za",
                            SupplierName = "KIC South Africa"
                        },
                        new
                        {
                            SupplierId = 456,
                            ContactNumber = "0317926900",
                            Email = "info@jusfridge.co.za",
                            SupplierName = "Just Refrigeration"
                        },
                        new
                        {
                            SupplierId = 123,
                            ContactNumber = "0861113804",
                            Email = "stedon@maxicoolsa.co.za",
                            SupplierName = "Maxi-Cool S.A"
                        },
                        new
                        {
                            SupplierId = 101,
                            ContactNumber = "0102071600",
                            Email = "enquiries@zeroappliances.co.za",
                            SupplierName = "Zero Appliances"
                        },
                        new
                        {
                            SupplierId = 112,
                            ContactNumber = "0823422002",
                            Email = "sales@minty.co.za",
                            SupplierName = "Mintys Factory Shop"
                        });
                });

            modelBuilder.Entity("Cool_Co_Fridge_Management.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Cool_Co_Fridge_Management.Models.Fridge_Stock", b =>
                {
                    b.HasOne("Cool_Co_Fridge_Management.Models.Fridge_Type", "Fridge_Type")
                        .WithMany()
                        .HasForeignKey("FridgeTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge_Type");
                });

            modelBuilder.Entity("Cool_Co_Fridge_Management.Models.Fridge_Type", b =>
                {
                    b.HasOne("Cool_Co_Fridge_Management.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
